IF(MSVC)
    LIST(APPEND CMAKE_PROGRAM_PATH "${PROJECT_SOURCE_DIR}/../swigwin-2.0.4")

    #LIST(APPEND CMAKE_PROGRAM_PATH "${PROJECT_SOURCE_DIR}/../3rdparty/x64/bin")
    #LIST(APPEND CMAKE_INCLUDE_PATH "${PROJECT_SOURCE_DIR}/../3rdparty/x64/include")
    #LIST(APPEND CMAKE_LIBRARY_PATH "${PROJECT_SOURCE_DIR}/../3rdparty/x64/lib")
ENDIF()
